# Notebook 1

In [61]:
import numpy as np

In [62]:
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

In [63]:
# Input Features
X = np.array([[10,14,18,16]])

In [64]:
# Initialising the weights
W = np.random.randn(4,3)
W

array([[ 0.54767458,  0.3321941 ,  0.78728503],
       [-2.21246422, -1.22853297,  1.09569202],
       [ 0.52538246,  1.02056597, -1.66735531],
       [-0.64909069, -0.18256249, -0.98494436]])

In [65]:
# Initialising the bias
B = np.random.rand(1,3)
B

array([[0.92255403, 0.92421282, 0.5534021 ]])

In [66]:
Z = X@(W)+ B
A = sigmoid(Z)

In [67]:
print("X shape :", X.shape)
print("W shape :", W.shape)
print("B shape :", B.shape)
print("Z shape :", Z.shape)
print("A shape :", A.shape)

X shape : (1, 4)
W shape : (4, 3)
B shape : (1, 3)
Z shape : (1, 3)
A shape : (1, 3)


In [68]:
A

array([[8.39180105e-12, 9.23852474e-01, 2.77398865e-10]])