# Notebook 3

In [ ]:
import numpy as np

In [50]:
class Dense:
    def __init__( self , input_size , output_size):
        self.W = np.random.randn( input_size , output_size )
        self.B = np.random.randn( 1 , output_size )

    def forward( self , X ):
        self.X = X
        self.Z = X@self.W + self.B
        return self.Z

In [51]:
class Sigmoid:
    def forward( self , Z):
        self.A =  1/(1 + np.exp(-Z))
        return self.A

    def backward(self):
        return self.A*( 1- self.A )

In [52]:
sigmoid1 = Sigmoid()
sigmoid2 = Sigmoid()
sigmoid3 = Sigmoid()

X = np.array([[10,14,18,16]])

layer1 = Dense(4,5)
Z1 = layer1.forward(X)
A1 = sigmoid1.forward(Z1)

layer2 = Dense(5,2)
Z2 = layer2.forward(A1)
A2 = sigmoid2.forward(Z2)

output_layer = Dense(2,1)
Z3 = output_layer.forward(A2)
A3 = sigmoid3.forward(Z3)

In [53]:
A3

array([[0.89488917]])

In [54]:
class Tanh:
    def forward(self,Z):
        self.A = np.tanh(Z)
        return self.A
        
    def backward(self):
        return 1-self.A**2

In [59]:
tanh1 = Tanh()
tanh2 = Tanh()
tanh3 = Tanh()

X = np.array([[10,14,18,16]])

layer1 = Dense(4,5)
Z1 = layer1.forward(X)
A1 = tanh1.forward(Z1)

layer2 = Dense(5,2)
Z2 = layer2.forward(A1)
A2 = tanh2.forward(Z2)

output_layer = Dense(2,1)
Z3 = output_layer.forward(A2)
A3 = tanh3.forward(Z3)

In [60]:
A3

array([[0.99540298]])

In [57]:
class ReLU:
    def forward(self,Z):
        self.Z = Z
        return np.maximum(0,Z)
        
    def backward(self): 
        return (self.Z>0).astype(float)

In [58]:
X = np.array([[10,14,18,16]])
layer1 = Dense(4,5)
Z1 = layer1.forward(X)

relu = ReLU()
A1 = relu.forward(Z1)

layer2 = Dense(5,2)
Z2 = layer2.forward(A1)
A2 = relu.forward(Z2)

output_layer = Dense(2,1)
Z3 = output_layer.forward(A2)
A3 = relu.forward(Z3)
A3

array([[1.75504918]])